version: '3'
services:
  python_app:
    container_name: python_app
    # pentru build, se va folosi directorul curent drept context
    # iar fisierul folosit pentru build de imagine va fi Dockerfile
    build: 
      context: .
    # stabilim portul pe care vrem sa il expunem pe host
    ports:
      - "5005:5000"
    # putem spune de ce alte containere depinde acest container
    depends_on:
      - postgres_demo_app
  
  postgres_demo_app:
    image: postgres:latest
    container_name: postgres_demo_app 
    # avem nevoie de parola custom pentru postgres pentru ca URI-ul este urmatorul: postgresql://postgres:4681188652@postgres_demo_app:5432/postgres
    environment:
      - POSTGRES_PASSWORD=4681188652
    ports:
      - "5431:5432"
    # cream volumul care ne va share-ui pe masina locala datele ce apartin bazei de date
    volumes:
      - "./postgres-db-data:/var/lib/postgresql/data"